export default class ProiectsService {
  data = [
    {
      title: "굿케어 홈페이지",
      subtitle: "(주)굿케어 홈페이지 리뉴얼 진행",
      bannerUrl: "",
      category: "site",
      tag: ["javascript", "기획", "web-site"],
      description: "",
      date: "",
      position: "",
      workHistory: [],
      git: null,
      homePageLink: null,
    },
    {
      title: "굿케어 사회서비스 웹 프로그램",
      subtitle: "사회서비스 전용 회계, 일정관리 프로그램 구축",
      bannerUrl: "",
      category: "program",
      tag: ["react", "javascript", "database"],
      description: "",
      date: "",
      position: "",
      workHistory: [],
      git: null,
      homePageLink: null,
    },
    {
      title: "3FS",
      subtitle: "디자인그룹 3FS 홈페이지 ",
      bannerUrl: "",
      category: "site",
      tag: ["javascript"],
      description: "",
      date: "",
      position: "",
      workHistory: [],
      git: null,
      homePageLink: null,
    },
    {
      title: "로켓회계",
      subtitle: "로켓회계 랜딩페이지와 서비스이용 확인페이지 ",
      bannerUrl: "",
      category: "site",
      tag: ["javascript"],
      description: "",
      date: "",
      position: "",
      workHistory: [],
      git: null,
      homePageLink: null,
    },
  ];
}
