export default class ProiectsService {
  data = [
    {
      title: '굿케어 홈페이지',
      subtitle: '(주)굿케어 홈페이지 리뉴얼 진행',
      url: '/projects/gd',
      bannerUrl: 'images/gd.jpg',
      category: 'site',
      tag: ['javascript', '기획', '스토리보드'],
      description: '',
      date: '2020',
      position: '',
      workHistory: [],
      git: null,
      homePageLink: null,
    },
    {
      title: '굿케어 사회서비스 웹 프로그램',
      subtitle: '사회서비스 전용 회계, 출결 일정관리 프로그램',
      url: '/projects/gs',
      bannerUrl: 'images/gs.jpg',
      category: 'program',
      tag: ['react', 'javascript', 'database', 'api'],
      description: '',
      date: '',
      position: '',
      workHistory: [],
      git: null,
      homePageLink: null,
    },
    {
      title: '3FS',
      subtitle: '디자인그룹 3FS 홈페이지 ',
      url: '/projects/fs',
      bannerUrl: 'images/fs2.jpg',
      category: 'site',
      tag: ['javascript', 'responsive'],
      description: '',
      date: '',
      position: '',
      workHistory: [],
      git: null,
      homePageLink: null,
    },
    {
      title: '로켓회계',
      subtitle: '로켓회계 랜딩페이지와 서비스이용 확인페이지 ',
      url: '/projects/ra',
      bannerUrl: 'images/ra.jpg',
      category: 'site',
      tag: ['javascript', 'responsive', 'design', 'landing page'],
      description: '',
      date: '',
      position: '',
      workHistory: [],
      git: null,
      homePageLink: null,
    },
  ];
}
