export default class ProiectsService {
  data = [
    {
      id: 'gs',
      title: '굿케어 사회서비스 웹 프로그램',
      subtitle: '사회서비스 전용 회계, 출결 일정관리 프로그램',
      link: 'https://goodcare-solution.com/login',
      url: '/projects/gs',
      bannerUrl: `${process.env.REACT_APP_BASE_URL}images/gs.jpg`,
      category: 'program',
      tag: ['react', 'javascript', 'database', 'api'],
      description: '',
      date: '2021',
      position: '',
      workHistory: [],
      git: null,
      homePageLink: null,
    },
    {
      id: 'gd',
      title: '굿케어 홈페이지',
      subtitle: '(주)굿케어 홈페이지 리뉴얼 진행',
      link: 'http://goodcare.me/',
      url: '/projects/gd',
      bannerUrl: `${process.env.REACT_APP_BASE_URL}images/gd.jpg`,
      category: 'site',
      tag: ['javascript', '기획', '스토리보드'],
      description: '',
      date: '2020',
      position: '',
      workHistory: [],
      git: null,
      homePageLink: null,
    },
    {
      id: 'fs',
      title: '3FS',
      subtitle: '디자인그룹 3FS 홈페이지 ',
      link: 'http://3fs-plus.com/',
      url: '/projects/fs',
      bannerUrl: `${process.env.REACT_APP_BASE_URL}images/fs2.jpg`,
      category: 'site',
      tag: ['javascript', 'responsive'],
      description: '',
      date: '',
      position: '',
      workHistory: [],
      git: null,
      homePageLink: null,
    },
    {
      id: 'ra',
      title: '로켓회계',
      subtitle: '로켓회계 랜딩페이지와 서비스이용 확인페이지 ',
      link: 'http://rocket-account.com/',
      url: '/projects/ra',
      bannerUrl: `${process.env.REACT_APP_BASE_URL}images/ra.jpg`,
      category: 'site',
      tag: ['javascript', 'responsive', 'design', 'landing page'],
      description: '',
      date: '',
      position: '',
      workHistory: [],
      git: null,
      homePageLink: null,
    },
  ];
}
